# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X402Cli < Formula
  desc "CLI tool for testing x402 payment-gated endpoints"
  homepage "https://github.com/razvanmacovei/x402-cli"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razvanmacovei/x402-cli/releases/download/v0.2.1/x402-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "2ecf7f1aaa95d66243aad8ed9974ec1d2fd54ed3f63197e4d9cd90de7339ca54"

      define_method(:install) do
        bin.install "x402-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razvanmacovei/x402-cli/releases/download/v0.2.1/x402-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "d09b30d83917b032164544170b16f3f3bb68fc3a5eed626b9a02f65cee45da37"

      define_method(:install) do
        bin.install "x402-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvanmacovei/x402-cli/releases/download/v0.2.1/x402-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "f7767c928010a2163c0debf87a5fa865783488646e21875db95d02849f20af8c"
      define_method(:install) do
        bin.install "x402-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvanmacovei/x402-cli/releases/download/v0.2.1/x402-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "598fbd6c194e7d16c25d98f498e7e6092628bcea8941e6a8158953c7a1bc4bd8"
      define_method(:install) do
        bin.install "x402-cli"
      end
    end
  end
end
